In [2]:
import pandas as pd

Files :
    
    sample csv file - https://github.com/codeforamerica/ohana-api/tree/master/data/sample-csv
    Titanic - https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv
    excel file - https://github.com/finbourne/sample-excel

In [3]:
ls

 Volume in drive E is Media
 Volume Serial Number is 7293-E2F1

 Directory of e:\FSDS 2.0\FSDS-Bootcamp-2.0\Class Notebook

05/04/2023  03:59 PM    <DIR>          .
05/04/2023  03:59 PM    <DIR>          ..
05/04/2023  03:41 PM           289,880 FSDS_1.0_Pandas_Day1_262.ipynb
05/04/2023  03:59 PM    <DIR>          Resources
05/01/2023  03:20 PM       574,072,999 zomato.csv
               2 File(s)    574,362,879 bytes
               3 Dir(s)  154,677,428,224 bytes free

In [4]:
pd.read_csv('E:\FSDS 2.0\FSDS-Bootcamp-2.0\Python\Pandas\pokemon_data.csv')

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [5]:
pd.read_csv("E:\FSDS 2.0\FSDS-Bootcamp-2.0\Class Notebook\Resources\locations.csv")

,id,organization_id,accessibility,admin_emails,alternate_name,description,email,languages,latitude,longitude,name,short_desc,transportation,website,virtual
0,1,1,"disabled_parking, ramp, restroom, wheelchair",NaN,NaN,A walk-in center for older adults that provide...,NaN,"Spanish, Tagalog",37.477227,-122.213221,Fair Oaks Adult Activity Center,A multipurpose senior citizens' center serving...,SAMTRANS stops in front.,NaN,False
1,2,1,wheelchair,NaN,NaN,Provides training and job placement to eligibl...,NaN,"Chinese (Mandarin), Tagalog, Italian, Spanish",37.563984,-122.325799,Second Career Employment Program,Provides training and job placement to eligibl...,"SAMTRANS stops within 1 block, CALTRAIN stops ...",NaN,False
2,3,1,NaN,NaN,NaN,Offers supportive counseling services to San M...,NaN,"Chinese (Cantonese), Chinese (Mandarin), Tagal...",37.563984,-122.325799,Senior Peer Counseling,Offers supportive counseling services to older...,Service is provided in person's home or at a m...,NaN,False
3,4,1,wheelchair,NaN,NaN,Provides supervised visitation services and a ...,NaN,Spanish,37.563984,-122.325799,Family Visitation Center,Provides supervised visitation services and a ...,"SAMTRANS stops within 1 block, CALTRAIN stops ...",NaN,False
4,5,1,wheelchair,NaN,NaN,Provides fixed 8% short term loans to eligible...,NaN,"Hindi, Spanish",37.563984,-122.325799,Economic Self - Sufficiency Program,Makes small loans to working families.,SAMTRANS stops within 1 block. CALTRAIN stops ...,NaN,False
5,6,2,"disabled_parking, wheelchair",NaN,NaN,A multipurpose center offering a wide variety ...,NaN,"Tagalog, Spanish",37.448020,-122.180590,Little House,A multipurpose senior citizens' center.,"SAMTRANS stops within 3 blocks, RediWheels and...",NaN,False
6,7,2,"ramp, restroom, disabled_parking, wheelchair",NaN,NaN,Rosener House is a day center for older adults...,NaN,"Spanish, Tagalog, Vietnamese",37.444178,-122.183093,Rosener House Adult Day Services,A day center for adults age 50 or over.,Transportation can be arranged via Redi-Wheels...,NaN,False
7,8,2,NaN,NaN,NaN,Delivers a hot meal to the home of persons age...,NaN,Spanish,37.448020,-122.180590,Meals on Wheels - South County,Will deliver a hot meal to the home of persons...,Not necessary for service.,NaN,False
8,9,3,"ramp, restroom, wheelchair",NaN,NaN,"Provides general reading material, including b...",NaN,Spanish,37.478502,-122.214143,Fair Oaks Branch,Provides general reading materials and referen...,SAMTRANS stops in front.,NaN,False
9,10,3,"elevator, tape_braille, ramp, restroom, disabl...",NaN,NaN,"Provides general reading and media materials, ...",NaN,Spanish,37.483842,-122.227395,Main Library,Provides general reference and reading materia...,SAMTRANS stops within 1 block; CALTRAIN stops ...,NaN,False
10,11,3,ramp,NaN,NaN,"Provides general reading materials, including ...",NaN,NaN,37.466553,-122.243090,Schaberg Branch,Provides general reading materials and referen...,SAMTRANS stops within 1 block.,NaN,False
11,12,3,"disabled_parking, elevator, ramp, restroom",ohana@gmail.com,NaN,Offers an intergenerational literacy program f...,NaN,NaN,37.483842,-122.227395,Project Read,Offers an intergenerational literacy program f...,SAMTRANS stops within 1 block.,NaN,False
12,13,3,NaN,NaN,NaN,"Provides general reading materials, including ...",NaN,NaN,37.530423,-122.258643,Redwood Shores Branch,Provides general reading materials and referen...,NaN,NaN,False
13,14,4,wheelchair,NaN,NaN,"Provides food, clothing, bus tokens and shelte...",NaN,Spanish,37.491386,-122.231568,Redwood City Corps,Provides a variety of emergency services to lo...,SAMTRANS stops nearby.,NaN,False
14,15,4,wheelchair,NaN,NaN,Provides a long-term (6-12 month) residential ...,NaN,Spanish,37.748899,-122.420367,Adult Rehabilitation Center,Long-term (6-12 month) residential treatment p...,"MUNI - 26 Valencia, Mission Street lines.",NaN,False
15,16,4,NaN,NaN,NaN,Provides emergency assistance including food a...,NaN,Korean,37.356900,-122.060002,Sunnyvale Corps,Provides emergency assistance to persons in im...,VTA stops within 4 blocks.,NaN,False
16,17,4,wheelchair,NaN,NaN,"Provides emergency food, clothing and furnitur...",NaN,NaN,37.644590,-122.422490,South San Francisco Citadel Corps,Provides emergency food and clothing and furni...,"SAMTRANS stops within 1 block, BART stops with...",NaN,False
17,18,5,"cd, restroom, wheelchair",NaN,NaN,Provides free medical care to those in need. O...,NaN,Spanish,37.468614,-122.206798,Redwood City Free Medical Clinic,Provides free medical care to those in need.,SAMTRANS stops within 2 blocks.,http://www.samaritanhouse.com,False
18,19,5,"elevator, ramp, wheelchair",NaN,NaN,Provides free medical and dental care to those...,NaN,Spanish,37.532694,-122.293124,San Mateo Free Medical Clinic,Provides free medical and dental care to those...,SAMTRANS stops within 1 block.,http://www.samaritanhouse.com,False
19,20,6,NaN,NaN,NaN,no phone,NaN,NaN,NaN,NaN,Location with no phone,no phone,NaN,NaN,True
20,21,7,"elevator, restroom",NaN,NaN,This is a description,NaN,NaN,37.529194,-122.287161,Admin Test Location,This is a short description,SAMTRANS stops within 1/2 mile.,NaN,False
21,22,8,"disabled_parking, restroom, wheelchair",foo@bar.com,The Test Spot,[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,info@example.org,"Cantonese, Russian, Spanish, Tagalog, Taiwanese",37.772640,-122.409915,Example Location,[NOTE THIS IS NOT A REAL ENTRY--THIS IS FOR TE...,SAMTRANS stops within 1 block,http://www.example.org,False

In [6]:
pd.read_csv('E:\FSDS 2.0\FSDS-Bootcamp-2.0\Class Notebook\Resources\services.csv')

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
2,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
3,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,NaN,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
4,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN
5,6,6,NaN,NaN,NaN,Walk in or apply by phone for membership appli...,Any age,A multipurpose center offering a wide variety ...,NaN,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, In-Home Su...",NaN,Little House Recreational Activities,NaN,San Mateo County,active,No wait.,NaN,NaN
6,7,7,NaN,NaN,NaN,"Apply by phone or be referred by a doctor, soc...","Older adults who have memory or sensory loss, ...",Rosener House is a day center for older adults...,Age 18 or over,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Adult Day ...",NaN,Rosener House Adult Day Services,NaN,"Belmont, Burlingame, East Palo Alto",active,No wait.,NaN,NaN
7,8,8,NaN,NaN,NaN,Apply by phone.,"Senior citizens age 60 or over, disabled indiv...",Delivers a hot meal to the home of persons age...,Homebound person unable to cook or shop,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Meals on Wheels - South County,NaN,"Belmont, East Palo Alto",active,No wait.,NaN,NaN
8,9,9,NaN,NaN,NaN,Walk in. Proof of residency in California requ...,"Ethnic minorities, especially Spanish speaking","Provides general reading material, including b...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Fair Oaks Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
9,10,10,NaN,NaN,NaN,Walk in. Proof of California residency to rece...,NaN,"Provides general reading and media materials, ...",Resident of California to obtain a card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Main Library,NaN,San Mateo County,active,No wait.,NaN,NaN
10,11,11,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library car...,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Schaberg Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
11,12,12,NaN,NaN,NaN,"Walk in or apply by phone, email or webpage re...","Adults, parents, children in 1st-12th grades i...",Offers an intergenerational literacy program f...,English-speaking adult reading at or below 7th...,NaN,...,NaN,"EDUCATION SERVICES, Adult, Alternative, Litera...",NaN,Project Read,NaN,Daly City,active,Depends on availability of tutors for small gr...,NaN,NaN
12,13,13,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Redwood Shores Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
13,14,14,NaN,NaN,NaN,Call for appointment. Referral from human serv...,Individuals or families with low or no income ...,"Provides food, clothing, bus tokens and shelte...",None for most services. For emergency assistan...,NaN,...,NaN,"COMMUNITY SERVICES, Interpretation/Translation...",NaN,Redwood City Corps,NaN,"Belmont, Burlingame, East Palo Alto",active,Up to 20 minutes.,NaN,NaN
14,15,15,NaN,NaN,NaN,Walk in or through other agency referral.,Adult alcoholic/drug addictive men and women w...,Provides a long-term (6-12 month) residential ...,"Age 21-60, detoxed, physically able and willin...",NaN,...,NaN,"ALCOHOLISM SERVICES, Residential Care, DRUG AB...",NaN,Adult Rehabilitation Center,NaN,"Alameda County, San Mateo County",active,Varies according to available beds for men and...,NaN,NaN
15,16,16,NaN,NaN,NaN,"Walk in. Written application, identification r...",NaN,Provides emergency assistance including food a...,None for emergency assistance,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,Sunnyvale Corps,NaN,NaN,active,No wait.,NaN,NaN
16,17,17,NaN,NaN,NaN,Call for information.,NaN,"Provides emergency food, clothing and furnitur...",Low-income families,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,South San Francisco Citadel Corps,NaN,"Colma, Daly City, South San Francisco",active,NaN,NaN,NaN
17,18,18,NaN,NaN,NaN,Call for screening appointment. Medical visits...,NaN,"By appointment only, Project Smile provides a ...",Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,Project Smile,NaN,East Palo Alto,active,Varies.,NaN,NaN
18,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
19,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
20,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
21,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,NaN,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
22,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,NaN,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [5]:
import pandas as pd
pd.read_csv("taxonomy.csv")

    taxonomy_id                          name parent_id           parent_name
0           101                     Emergency       NaN                   NaN
1        101-01             Disaster Response       101             Emergency
2        101-02                Emergency Cash       101             Emergency
3     101-02-01             Help Pay for Food    101-02        Emergency Cash
4     101-02-02       Help Pay for Healthcare    101-02        Emergency Cash
..          ...                           ...       ...                   ...
285   111-01-07              Workplace Rights    111-01  Advocacy & Legal Aid
286      111-02                     Mediation       111                 Legal
287      111-03                        Notary       111                 Legal
288      111-04                Representation       111                 Legal
289      111-05  Translation & Interpretation       111                 Legal

[290 rows x 4 columns]

In [6]:
df = pd.read_csv('taxonomy.csv')

In [7]:
a = 1

In [8]:
type(a)

int

In [12]:
type(df)

pandas.core.frame.DataFrame

In [13]:
pd.read_csv('taxonomy.csv',header=None)

,0,1,2,3
0,taxonomy_id,name,parent_id,parent_name
1,101,Emergency,NaN,NaN
2,101-01,Disaster Response,101,Emergency
3,101-02,Emergency Cash,101,Emergency
4,101-02-01,Help Pay for Food,101-02,Emergency Cash
...,...,...,...,...
286,111-01-07,Workplace Rights,111-01,Advocacy & Legal Aid
287,111-02,Mediation,111,Legal
288,111-03,Notary,111,Legal
289,111-04,Representation,111,Legal
290,111-05,Translation & Interpretation,111,Legal

In [17]:
pd.read_csv('taxonomy.csv',names =['abc','b','c','d','e'])

,abc,b,c,d,e
0,taxonomy_id,name,parent_id,parent_name,NaN
1,101,Emergency,NaN,NaN,NaN
2,101-01,Disaster Response,101,Emergency,NaN
3,101-02,Emergency Cash,101,Emergency,NaN
4,101-02-01,Help Pay for Food,101-02,Emergency Cash,NaN
...,...,...,...,...,...
286,111-01-07,Workplace Rights,111-01,Advocacy & Legal Aid,NaN
287,111-02,Mediation,111,Legal,NaN
288,111-03,Notary,111,Legal,NaN
289,111-04,Representation,111,Legal,NaN
290,111-05,Translation & Interpretation,111,Legal,NaN

In [20]:
pd.read_csv('taxonomy.csv',names =['abc','b']) #applied to, from left to right.

                                                abc                     b
taxonomy_id name                          parent_id           parent_name
101         Emergency                           NaN                   NaN
101-01      Disaster Response                   101             Emergency
101-02      Emergency Cash                      101             Emergency
101-02-01   Help Pay for Food                101-02        Emergency Cash
...                                             ...                   ...
111-01-07   Workplace Rights                 111-01  Advocacy & Legal Aid
111-02      Mediation                           111                 Legal
111-03      Notary                              111                 Legal
111-04      Representation                      111                 Legal
111-05      Translation & Interpretation        111                 Legal

[291 rows x 2 columns]

In [24]:
pd.read_csv('taxonomy.csv' ,names=["adfgfadssaf" , 'b' ] )

                                       adfgfadssaf                     b
101       Emergency                            NaN                   NaN
101-01    Disaster Response                    101             Emergency
101-02    Emergency Cash                       101             Emergency
101-02-01 Help Pay for Food                 101-02        Emergency Cash
101-02-02 Help Pay for Healthcare           101-02        Emergency Cash
...                                            ...                   ...
111-01-07 Workplace Rights                  111-01  Advocacy & Legal Aid
111-02    Mediation                            111                 Legal
111-03    Notary                               111                 Legal
111-04    Representation                       111                 Legal
111-05    Translation & Interpretation         111                 Legal

[290 rows x 2 columns]

In [25]:
pd.read_csv('sample_test.csv')

       name                 emailid    address  pin code         sirname
0  sudhanshu  SSKUMAR9876@GMAIL.COM  Bengalore     560085          kumar
1     krish         krish@gmail.com  bengalore     560085           naik
2    ineuron     ineuron@ineuron.ai  Bengalore     560085  intelligence
3     pandas      pandas@ineuron.ai    chennai   25845121       tutorial

In [27]:
pd.read_csv('sample_test.csv',sep='@')

                 name      emailid    address  pin code         sirname
sudhanshu  SSKUMAR9876   GMAIL.COM  Bengalore     560085          kumar
krish            krish   gmail.com  bengalore     560085           naik
ineuron        ineuron  ineuron.ai  Bengalore     560085  intelligence
pandas          pandas  ineuron.ai    chennai   25845121       tutorial

In [31]:
df = pd.read_csv('sample_test.csv',sep='|')

In [32]:
df

       name                 emailid    address  pin code         sirname
0  sudhanshu  SSKUMAR9876@GMAIL.COM  Bengalore     560085          kumar
1     krish         krish@gmail.com  bengalore     560085           naik
2    ineuron     ineuron@ineuron.ai  Bengalore     560085  intelligence
3     pandas      pandas@ineuron.ai    chennai   25845121       tutorial

In [24]:
pd.read_csv('taxonomy.csv',sep=',' , skiprows=[1,4])

    taxonomy_id                          name parent_id           parent_name
0        101-01             Disaster Response       101             Emergency
1        101-02                Emergency Cash       101             Emergency
2     101-02-02       Help Pay for Healthcare    101-02        Emergency Cash
3     101-02-03          Help Pay for Housing    101-02        Emergency Cash
4     101-02-04              Help Pay for Gas    101-02        Emergency Cash
..          ...                           ...       ...                   ...
283   111-01-07              Workplace Rights    111-01  Advocacy & Legal Aid
284      111-02                     Mediation       111                 Legal
285      111-03                        Notary       111                 Legal
286      111-04                Representation       111                 Legal
287      111-05  Translation & Interpretation       111                 Legal

[288 rows x 4 columns]

In [28]:
pd.read_csv('E:\FSDS 2.0\FSDS-Bootcamp-2.0\Class Notebook\Resources\mail_addresses.csv',sep=',' , skiprows=[2,3])

,id,location_id,attention,address_1,address_2,city,state_province,postal_code,country
0,1,1,Fair Oaks Intergenerational Center,2600 Middlefield Road,NaN,Redwood City,CA,94063,US
1,4,4,PFS Family Visitation Center,24 Second Avenue,NaN,San Mateo,CA,94401,US
2,5,5,Economic Self - Sufficiency Program,24 Second Avenue,NaN,San Mateo,CA,94401,US
3,6,6,Little House,800 Middle Avenue,NaN,Menlo Park,CA,94025-9881,US
4,7,7,Rosener House,500 Arbor Road,NaN,Menlo Park,CA,94025,US
5,8,8,Meals on Wheels - South County,800 Middle Avenue,NaN,Menlo Park,CA,94025-9881,US
6,9,9,Fair Oaks Branch,2510 Middlefield Road,NaN,Redwood City,CA,94063,US
7,10,10,Main Library,1044 Middlefield Road,NaN,Redwood City,CA,94063,US
8,11,11,Schaberg Branch,2140 Euclid Avenue,NaN,Redwood City,CA,94061,US
9,12,12,Project Read,1044 Middlefield Road,2nd Floor,Redwood City,CA,94063,US
10,13,13,Redwood Shores Branch,399 Marine Parkway,NaN,Redwood City,CA,94065,US
11,14,14,Salvation Army,P.O. Box 1147,NaN,Redwood City,CA,94064,US
12,15,15,Adult Rehabilitation Center,1500 Valencia Street,NaN,San Francisco,CA,94110,US
13,16,16,Salvation Army,P.O. Box 61868,NaN,Sunnyvale,CA,94088,US
14,17,17,Salvation Army,409 South Spruce Avenue,NaN,South San Francisco,CA,94080,US
15,18,18,Redwood City Free Medical Clinic,114 Fifth Avenue,NaN,Redwood City,CA,94063,US
16,19,19,San Mateo Free Medical/Dental,19 West 39th Avenue,NaN,San Mateo,CA,94403,US
17,20,20,NaN,123 Main Street,NaN,Fairfax,VA,22031,US
18,21,22,The Foodies,2013 Avenue of the fellows,Suite 100,San Francisco,CA,90210,US

In [ ]:
df1 = pd.read_csv('sample_test.csv',sep='|' , skiprows=[1,3])

In [ ]:
df1

    name             emailid    address  pin code    sirname
0  krish     krish@gmail.com  bengalore     560085      naik
1  pandas  pandas@ineuron.ai    chennai   25845121  tutorial

In [29]:
df = pd.read_csv('E:\FSDS 2.0\FSDS-Bootcamp-2.0\Class Notebook\Resources\services.csv')

In [30]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df.dtypes

id                           int64
location_id                  int64
program_id                 float64
accepted_payments           object
alternate_name              object
application_process         object
audience                    object
description                 object
eligibility                 object
email                       object
fees                        object
funding_sources             object
interpretation_services     object
keywords                    object
languages                   object
name                        object
required_documents          object
service_areas               object
status                      object
wait_time                   object
website                     object
taxonomy_ids                object
dtype: object

In [31]:
df

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
2,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
3,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,NaN,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
4,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN
5,6,6,NaN,NaN,NaN,Walk in or apply by phone for membership appli...,Any age,A multipurpose center offering a wide variety ...,NaN,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, In-Home Su...",NaN,Little House Recreational Activities,NaN,San Mateo County,active,No wait.,NaN,NaN
6,7,7,NaN,NaN,NaN,"Apply by phone or be referred by a doctor, soc...","Older adults who have memory or sensory loss, ...",Rosener House is a day center for older adults...,Age 18 or over,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Adult Day ...",NaN,Rosener House Adult Day Services,NaN,"Belmont, Burlingame, East Palo Alto",active,No wait.,NaN,NaN
7,8,8,NaN,NaN,NaN,Apply by phone.,"Senior citizens age 60 or over, disabled indiv...",Delivers a hot meal to the home of persons age...,Homebound person unable to cook or shop,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Meals on Wheels - South County,NaN,"Belmont, East Palo Alto",active,No wait.,NaN,NaN
8,9,9,NaN,NaN,NaN,Walk in. Proof of residency in California requ...,"Ethnic minorities, especially Spanish speaking","Provides general reading material, including b...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Fair Oaks Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
9,10,10,NaN,NaN,NaN,Walk in. Proof of California residency to rece...,NaN,"Provides general reading and media materials, ...",Resident of California to obtain a card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Main Library,NaN,San Mateo County,active,No wait.,NaN,NaN
10,11,11,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library car...,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Schaberg Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
11,12,12,NaN,NaN,NaN,"Walk in or apply by phone, email or webpage re...","Adults, parents, children in 1st-12th grades i...",Offers an intergenerational literacy program f...,English-speaking adult reading at or below 7th...,NaN,...,NaN,"EDUCATION SERVICES, Adult, Alternative, Litera...",NaN,Project Read,NaN,Daly City,active,Depends on availability of tutors for small gr...,NaN,NaN
12,13,13,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Redwood Shores Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
13,14,14,NaN,NaN,NaN,Call for appointment. Referral from human serv...,Individuals or families with low or no income ...,"Provides food, clothing, bus tokens and shelte...",None for most services. For emergency assistan...,NaN,...,NaN,"COMMUNITY SERVICES, Interpretation/Translation...",NaN,Redwood City Corps,NaN,"Belmont, Burlingame, East Palo Alto",active,Up to 20 minutes.,NaN,NaN
14,15,15,NaN,NaN,NaN,Walk in or through other agency referral.,Adult alcoholic/drug addictive men and women w...,Provides a long-term (6-12 month) residential ...,"Age 21-60, detoxed, physically able and willin...",NaN,...,NaN,"ALCOHOLISM SERVICES, Residential Care, DRUG AB...",NaN,Adult Rehabilitation Center,NaN,"Alameda County, San Mateo County",active,Varies according to available beds for men and...,NaN,NaN
15,16,16,NaN,NaN,NaN,"Walk in. Written application, identification r...",NaN,Provides emergency assistance including food a...,None for emergency assistance,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,Sunnyvale Corps,NaN,NaN,active,No wait.,NaN,NaN
16,17,17,NaN,NaN,NaN,Call for information.,NaN,"Provides emergency food, clothing and furnitur...",Low-income families,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,South San Francisco Citadel Corps,NaN,"Colma, Daly City, South San Francisco",active,NaN,NaN,NaN
17,18,18,NaN,NaN,NaN,Call for screening appointment. Medical visits...,NaN,"By appointment only, Project Smile provides a ...",Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,Project Smile,NaN,East Palo Alto,active,Varies.,NaN,NaN
18,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
19,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
20,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
21,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,NaN,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
22,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,NaN,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [32]:
df.head(2)

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN

In [33]:
df.head(2)

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN

In [34]:
df.tail(3)

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
20,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
21,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,NaN,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
22,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,NaN,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [35]:
df.tail(2)

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
21,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,NaN,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
22,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,NaN,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [37]:
df. columns

Index(['id', 'location_id', 'program_id', 'accepted_payments',
       'alternate_name', 'application_process', 'audience', 'description',
       'eligibility', 'email', 'fees', 'funding_sources',
       'interpretation_services', 'keywords', 'languages', 'name',
       'required_documents', 'service_areas', 'status', 'wait_time', 'website',
       'taxonomy_ids'],
      dtype='object')

In [41]:
for i in df. columns:
    print(i)

id
location_id
program_id
accepted_payments
alternate_name
application_process
audience
description
eligibility
email
fees
funding_sources
interpretation_services
keywords
languages
name
required_documents
service_areas
status
wait_time
website
taxonomy_ids

In [42]:
df.dtypes

id                           int64
location_id                  int64
program_id                 float64
accepted_payments           object
alternate_name              object
application_process         object
audience                    object
description                 object
eligibility                 object
email                       object
fees                        object
funding_sources             object
interpretation_services     object
keywords                    object
languages                   object
name                        object
required_documents          object
service_areas               object
status                      object
wait_time                   object
website                     object
taxonomy_ids                object
dtype: object

In [ ]:
df

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
2,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
3,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,None,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
4,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN
5,6,6,NaN,NaN,NaN,Walk in or apply by phone for membership appli...,Any age,A multipurpose center offering a wide variety ...,None,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, In-Home Su...",NaN,Little House Recreational Activities,NaN,San Mateo County,active,No wait.,NaN,NaN
6,7,7,NaN,NaN,NaN,"Apply by phone or be referred by a doctor, soc...","Older adults who have memory or sensory loss, ...",Rosener House is a day center for older adults...,Age 18 or over,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Adult Day ...",NaN,Rosener House Adult Day Services,NaN,"Belmont, Burlingame, East Palo Alto",active,No wait.,NaN,NaN
7,8,8,NaN,NaN,NaN,Apply by phone.,"Senior citizens age 60 or over, disabled indiv...",Delivers a hot meal to the home of persons age...,Homebound person unable to cook or shop,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Meals on Wheels - South County,NaN,"Belmont, East Palo Alto",active,No wait.,NaN,NaN
8,9,9,NaN,NaN,NaN,Walk in. Proof of residency in California requ...,"Ethnic minorities, especially Spanish speaking","Provides general reading material, including b...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Fair Oaks Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
9,10,10,NaN,NaN,NaN,Walk in. Proof of California residency to rece...,NaN,"Provides general reading and media materials, ...",Resident of California to obtain a card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Main Library,NaN,San Mateo County,active,No wait.,NaN,NaN
10,11,11,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library car...,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Schaberg Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
11,12,12,NaN,NaN,NaN,"Walk in or apply by phone, email or webpage re...","Adults, parents, children in 1st-12th grades i...",Offers an intergenerational literacy program f...,English-speaking adult reading at or below 7th...,NaN,...,NaN,"EDUCATION SERVICES, Adult, Alternative, Litera...",NaN,Project Read,NaN,Daly City,active,Depends on availability of tutors for small gr...,NaN,NaN
12,13,13,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Redwood Shores Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
13,14,14,NaN,NaN,NaN,Call for appointment. Referral from human serv...,Individuals or families with low or no income ...,"Provides food, clothing, bus tokens and shelte...",None for most services. For emergency assistan...,NaN,...,NaN,"COMMUNITY SERVICES, Interpretation/Translation...",NaN,Redwood City Corps,NaN,"Belmont, Burlingame, East Palo Alto",active,Up to 20 minutes.,NaN,NaN
14,15,15,NaN,NaN,NaN,Walk in or through other agency referral.,Adult alcoholic/drug addictive men and women w...,Provides a long-term (6-12 month) residential ...,"Age 21-60, detoxed, physically able and willin...",NaN,...,NaN,"ALCOHOLISM SERVICES, Residential Care, DRUG AB...",NaN,Adult Rehabilitation Center,NaN,"Alameda County, San Mateo County",active,Varies according to available beds for men and...,NaN,NaN
15,16,16,NaN,NaN,NaN,"Walk in. Written application, identification r...",NaN,Provides emergency assistance including food a...,None for emergency assistance,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,Sunnyvale Corps,NaN,NaN,active,No wait.,NaN,NaN
16,17,17,NaN,NaN,NaN,Call for information.,NaN,"Provides emergency food, clothing and furnitur...",Low-income families,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,South San Francisco Citadel Corps,NaN,"Colma, Daly City, South San Francisco",active,NaN,NaN,NaN
17,18,18,NaN,NaN,NaN,Call for screening appointment. Medical visits...,NaN,"By appointment only, Project Smile provides a ...",Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,Project Smile,NaN,East Palo Alto,active,Varies.,NaN,NaN
18,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
19,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
20,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
21,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,None,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
22,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,None,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [ ]:
df.columns

Index(['id', 'location_id', 'program_id', 'accepted_payments',
       'alternate_name', 'application_process', 'audience', 'description',
       'eligibility', 'email', 'fees', 'funding_sources',
       'interpretation_services', 'keywords', 'languages', 'name',
       'required_documents', 'service_areas', 'status', 'wait_time', 'website',
       'taxonomy_ids'],
      dtype='object')

In [43]:
df['name']

0          Fair Oaks Adult Activity Center
1         Second Career Employment Program
2                   Senior Peer Counseling
3                 Family Visitation Center
4        Economic Self-Sufficiency Program
5     Little House Recreational Activities
6         Rosener House Adult Day Services
7           Meals on Wheels - South County
8                         Fair Oaks Branch
9                             Main Library
10                         Schaberg Branch
11                            Project Read
12                   Redwood Shores Branch
13                      Redwood City Corps
14             Adult Rehabilitation Center
15                         Sunnyvale Corps
16       South San Francisco Citadel Corps
17                           Project Smile
18           San Mateo Free Medical Clinic
19               Service with blank fields
20         Service for Admin Test Location
21                         Passport Photos
22                    Example Service Name
Name: name, dtype: object

In [45]:
df["keywords"]

0     ADULT PROTECTION AND CARE SERVICES, Meal Sites...
1     EMPLOYMENT/TRAINING SERVICES, Job Development,...
2     Geriatric Counseling, Older Adults, Gay, Lesbi...
3     INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...
4        COMMUNITY SERVICES, Speakers, Automobile Loans
5     ADULT PROTECTION AND CARE SERVICES, In-Home Su...
6     ADULT PROTECTION AND CARE SERVICES, Adult Day ...
7     ADULT PROTECTION AND CARE SERVICES, Meal Sites...
8     EDUCATION SERVICES, Library, Libraries, Public...
9     EDUCATION SERVICES, Library, Libraries, Public...
10    EDUCATION SERVICES, Library, Libraries, Public...
11    EDUCATION SERVICES, Adult, Alternative, Litera...
12    EDUCATION SERVICES, Library, Libraries, Public...
13    COMMUNITY SERVICES, Interpretation/Translation...
14    ALCOHOLISM SERVICES, Residential Care, DRUG AB...
15    COMMODITY SERVICES, Clothing/Personal Items, C...
16    COMMODITY SERVICES, Clothing/Personal Items, C...
17    HEALTH SERVICES, Outpatient Care, Community Cl...
18    HEALTH SERVICES, Outpatient Care, Community Cl...
19                                                  NaN
20                                                  NaN
21                                      Salud, Medicina
22           Ruby on Rails/Postgres/Redis, testing, wic
Name: keywords, dtype: object

In [46]:
a = df["name"]

In [47]:
type(a)

pandas.core.series.Series

In [48]:
df1 = df["name" ,'location_id','id' ] #Not return output beacuse more than once columns

KeyError: ('name', 'location_id', 'id')

In [50]:
df[["name" ,'location_id','id' ]] #when have more than one columns, need to enclosed with in squre bracket like [[]].

                                    name  location_id  id
0        Fair Oaks Adult Activity Center            1   1
1       Second Career Employment Program            2   2
2                 Senior Peer Counseling            3   3
3               Family Visitation Center            4   4
4      Economic Self-Sufficiency Program            5   5
5   Little House Recreational Activities            6   6
6       Rosener House Adult Day Services            7   7
7         Meals on Wheels - South County            8   8
8                       Fair Oaks Branch            9   9
9                           Main Library           10  10
10                       Schaberg Branch           11  11
11                          Project Read           12  12
12                 Redwood Shores Branch           13  13
13                    Redwood City Corps           14  14
14           Adult Rehabilitation Center           15  15
15                       Sunnyvale Corps           16  16
16     South San Francisco Citadel Corps           17  17
17                         Project Smile           18  18
18         San Mateo Free Medical Clinic           19  19
19             Service with blank fields           20  20
20       Service for Admin Test Location           21  21
21                       Passport Photos           22  22
22                  Example Service Name           22  23

In [51]:
df1 = df[["name" ,'location_id','id' ]]

In [52]:
type(df1)

pandas.core.frame.DataFrame

In [53]:
type(df[['name']])

pandas.core.frame.DataFrame

In [54]:
ls

 Volume in drive E is Media
 Volume Serial Number is 7293-E2F1

 Directory of e:\FSDS 2.0\FSDS-Bootcamp-2.0\Class Notebook

05/04/2023  04:30 PM    <DIR>          .
05/04/2023  04:30 PM    <DIR>          ..
05/04/2023  05:13 PM           339,554 FSDS_1.0_Pandas_Day1_262.ipynb
05/04/2023  04:30 PM    <DIR>          Resources
04/26/2023  03:23 PM            14,618 taxonomy.csv
05/01/2023  03:20 PM       574,072,999 zomato.csv
               3 File(s)    574,427,171 bytes
               3 Dir(s)  154,677,379,072 bytes free

In [2]:
import pandas as pd
pd.read_excel("E:\FSDS 2.0\FSDS-Bootcamp-2.0\Class Notebook\Resources\LUSID Excel - Manage Orders.xlsx")

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
0,NaN,This sheet allows you to manage executions:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,1. List executions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,2. Get execution,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,3. Upsert executions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,NaN,NaN,Code,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,NaN,NaN,MyExecutionCode01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
pd.read_excel('E:\FSDS 2.0\FSDS-Bootcamp-2.0\Class Notebook\Resources\LUSID Excel - Manage Orders.xlsx',sheet_name = "Allocations")

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21
0,NaN,This sheet allows you to manage Allocations:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,1. ListAllocations,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,2. GetAllocation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,3. UpsertAllocations,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,NaN,NaN,Code,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,NaN,NaN,MyAllocation001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,NaN,NaN,MyAllocation002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df = pd.read_excel('E:\FSDS 2.0\FSDS-Bootcamp-2.0\Class Notebook\Resources\LUSID Excel - Manage Orders.xlsx')

In [6]:
df.keys()

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18'],
      dtype='object')

In [8]:
df = pd.ExcelFile('E:\FSDS 2.0\FSDS-Bootcamp-2.0\Class Notebook\Resources\LUSID Excel - Manage Orders.xlsx')

In [9]:
df.sheet_names

['Executions', 'Orders', 'Allocations', 'Placements', 'Blocks']

In [11]:
pd.read_excel('E:\FSDS 2.0\FSDS-Bootcamp-2.0\Class Notebook\Resources\LUSID Excel - Manage Orders.xlsx',sheet_name = "Blocks")

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,NaN,This sheet allows you to manage Blocks:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,1. ListBlocks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,2. GetBlock,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,3. UpsertBlocks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,1. Get a list of blocks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,asAt:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,filter:,quantity gt 50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,propertyKeys:,Block/MyScope/SomeOrderEntityProperty,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,Id Scope,Id Code,OrderIds,InstrumentIdentifiers,LusidInstrumentId,Quantity,Side,Type,TimeInForce,CreatedDate,LimitPrice Amount,LimitPrice Currency,StopPrice Amount,StopPrice Currency,Test Property for MyScope
17,NaN,NaN,TestScope2,orderEntityCode2,TestScope2:testOrder,Instrument/default/Name:ABC123,LUID_ZZZZZZZZ,100,Buy,GTC,Market,2020-10-10 00:00:00,2468,GBP,1357,GBP,0
18,NaN,NaN,TestScope,OrderEntity6,TestScope:testOrder,Instrument/default/Figi:INSTR1,LUID_ZZZZZZZZ,100,Buy,GTC,Market,2020-10-10 00:00:00,2468,GBP,1357,GBP,testValue1
19,NaN,NaN,TestScope,OrderEntity1,TestScope:testOrder,Instrument/default/Figi:INSTR1,LUID_ZZZZZZZZ,100,Buy,GTC,Market,2020-10-10 00:00:00,2468,GBP,1357,GBP,testValue1
20,NaN,NaN,TestScope,OrderEntity5,TestScope:testOrder,Instrument/default/Figi:INSTR1,LUID_ZZZZZZZZ,100,Buy,GTC,Market,2020-10-10 00:00:00,2468,GBP,1357,GBP,testValue1
21,NaN,NaN,TestScope,OrderEntity2,TestScope:testOrder,Instrument/default/Figi:INSTR1,LUID_ZZZZZZZZ,100,Buy,GTC,Market,2020-10-10 00:00:00,2468,GBP,1357,GBP,testValue1
22,NaN,NaN,TestScope,OrderEntity4,TestScope:testOrder,Instrument/default/Figi:INSTR1,LUID_ZZZZZZZZ,100,Buy,GTC,Market,2020-10-10 00:00:00,2468,GBP,1357,GBP,testValue1
23,NaN,NaN,TestScope,OrderEntity3,TestScope:testOrder,Instrument/default/Figi:INSTR1,LUID_ZZZZZZZZ,100,Buy,GTC,Market,2020-10-10 00:00:00,2468,GBP,1357,GBP,testValue1
24,NaN,NaN,TestScope,orderEntityCode1,TestScope:testOrder,Instrument/default/Name:ABC123,LUID_ZZZZZZZZ,100,Buy,GTC,Market,2020-10-10 00:00:00,2468,GBP,1357,GBP,0
25,NaN,NaN,TestScope,BLOC_1310500833,TestScope:ORD_805415329,"Instrument/default/Ticker:AMZN,Instrument/defa...",LUID_3QJOY75Q,2342,Buy,Good Til Canceled,Limit,2020-01-01 01:02:03,0,CCY_ZZZ,34.81,USD,0
26,NaN,NaN,TestScope,BLOC_949780324,TestScope:ORD_98041040,"Instrument/default/Ticker:VOD,Instrument/defau...",LUID_LP8MS5OS,2189,Buy,Good Til Canceled,Limit,2020-01-01 01:02:03,0,CCY_ZZZ,34.81,USD,0
27,NaN,NaN,TestScopeOrderGraph,BLOC_1842506452,TestScopeOrderGraph:ORD_265037669,"Instrument/default/Ticker:AAPL,Instrument/defa...",LUID_JUE15W3W,2190,Buy,Good Til Canceled,Limit,2020-01-01 01:02:03,0,CCY_ZZZ,34.81,USD,0
28,NaN,NaN,[More...],[More...],[More...],[More...],[More...],[More...],[More...],[More...],[More...],[More...],[More...],[More...],[More...],[More...],[More...]
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,2. Get a specific block,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,scope:,TestScope,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,code:,OrderEntity1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,asAt:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,NaN,propertyKeys:,Block/MyScope/SomeOrderEntityProperty,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,NaN,NaN,Id Scope,Id Code,OrderIds,InstrumentIdentifiers,LusidInstrumentId,Quantity,Side,Type,TimeInForce,CreatedDate,LimitPrice Amount,LimitPrice Currency,StopPrice Amount,StopPrice Currency,Test Property for MyScope
42,NaN,NaN,TestScope,OrderEntity1,TestScope:testOrder,Instrument/default/Figi:INSTR1,LUID_ZZZZZZZZ,100,Buy,GTC,Market,2020-10-10 00:00:00,2468,GBP,1357,GBP,testValue1
43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,NaN,3. Upsert blocks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,NaN,Add blocks using the following table:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,NaN,NaN,Id Scope,Id Code,OrderIds,Instrument Id Types,Instrument Ids,Quantity,Side,Type,TimeInForce,CreatedDate,LimitPrice Amount,LimitPrice Currency,StopPrice Amount,StopPrice Currency,NaN
50,NaN,NaN,TestScope,MyOrder001,TestScope:testOrder,Instrument/default/Figi,INSTR1,150,Buy,Market,GTC,2022-01-06 00:00:00,10,GBP,10,GBP,NaN
51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,NaN,NaN,Code,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,NaN,NaN,MyOrder001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
for i in df.sheet_names:
    pd.read_excel('E:\FSDS 2.0\FSDS-Bootcamp-2.0\Class Notebook\Resources\LUSID Excel - Manage Orders.xlsx' , sheet_name=i)

In [12]:
pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
pd.read_csv('https://raw.githubusercontent.com/codeforamerica/ohana-api/master/data/sample-csv/phones.csv')

,id,contact_id,location_id,organization_id,service_id,country_prefix,department,extension,number,number_type,vanity_number
0,1,NaN,1.0,NaN,NaN,NaN,NaN,NaN,650 780-7525,voice,NaN
1,2,NaN,1.0,NaN,NaN,NaN,NaN,NaN,650 701-0856,fax,NaN
2,3,NaN,2.0,NaN,NaN,NaN,NaN,4385.0,650 403-4300,voice,NaN
3,4,NaN,2.0,NaN,NaN,NaN,NaN,NaN,650 403-4302,fax,NaN
4,5,NaN,3.0,NaN,NaN,NaN,English,NaN,650 403-4300,voice,NaN
5,6,NaN,3.0,NaN,NaN,NaN,NaN,NaN,650 403-4303,fax,NaN
6,7,NaN,4.0,NaN,NaN,NaN,NaN,4500.0,650 403-4300,voice,NaN
7,8,NaN,4.0,NaN,NaN,NaN,NaN,NaN,650 403-4303,fax,NaN
8,9,NaN,5.0,NaN,NaN,NaN,NaN,4100.0,650 403-4300,voice,NaN
9,10,NaN,5.0,NaN,NaN,NaN,NaN,NaN,650 403-4303,fax,NaN
10,11,NaN,6.0,NaN,NaN,NaN,NaN,NaN,650 326-2025,voice,NaN
11,12,NaN,6.0,NaN,NaN,NaN,NaN,NaN,650 326-9547,fax,NaN
12,13,NaN,7.0,NaN,NaN,NaN,NaN,NaN,650 322-0126,voice,NaN
13,14,NaN,7.0,NaN,NaN,NaN,NaN,NaN,650 322-4067,fax,NaN
14,15,NaN,8.0,NaN,NaN,NaN,NaN,NaN,650 323-2022,voice,NaN
15,16,NaN,8.0,NaN,NaN,NaN,NaN,NaN,650 326-9547,fax,NaN
16,17,NaN,9.0,NaN,NaN,NaN,NaN,NaN,650 780-7261,voice,NaN
17,18,NaN,9.0,NaN,NaN,NaN,NaN,NaN,650 569-3371,fax,NaN
18,19,NaN,10.0,NaN,NaN,NaN,Circulation,NaN,650 780-7018,voice,NaN
19,20,NaN,10.0,NaN,NaN,NaN,NaN,NaN,650 780-7069,fax,NaN
20,21,NaN,11.0,NaN,NaN,NaN,NaN,NaN,650 780-7010,voice,NaN
21,23,NaN,12.0,NaN,NaN,NaN,NaN,NaN,650 780-7077,voice,NaN
22,24,NaN,12.0,NaN,NaN,NaN,NaN,NaN,650 780-7004,fax,NaN
23,25,NaN,13.0,NaN,NaN,NaN,NaN,NaN,650 780-5740,voice,NaN
24,26,NaN,14.0,NaN,NaN,NaN,NaN,NaN,650 368-4643,voice,NaN
25,27,NaN,14.0,NaN,NaN,NaN,NaN,NaN,650 364-1712,fax,NaN
26,28,NaN,15.0,NaN,NaN,NaN,NaN,NaN,415 643-8000,voice,NaN
27,29,NaN,15.0,NaN,NaN,NaN,NaN,NaN,415 285-1391,fax,NaN
28,30,NaN,16.0,NaN,NaN,NaN,NaN,NaN,408 720-0420,voice,NaN
29,31,NaN,16.0,NaN,NaN,NaN,NaN,NaN,408 720-8075,fax,NaN
30,32,NaN,17.0,NaN,NaN,NaN,NaN,NaN,650 266-4591,voice,NaN
31,33,NaN,17.0,NaN,NaN,NaN,NaN,NaN,650 266-2594,fax,NaN
32,34,NaN,17.0,NaN,NaN,NaN,NaN,NaN,650 266-4594,fax,NaN
33,35,NaN,18.0,NaN,NaN,NaN,NaN,NaN,650 839-1447,voice,NaN
34,36,NaN,18.0,NaN,NaN,NaN,NaN,NaN,650 839-1457,fax,NaN
35,37,NaN,19.0,NaN,NaN,NaN,NaN,NaN,650 578-0400,voice,NaN
36,38,NaN,19.0,NaN,NaN,NaN,NaN,NaN,650 578-0440,fax,NaN
37,39,NaN,21.0,NaN,NaN,NaN,CalFresh,1223.0,7035551212,voice,703-555-ABCD
38,40,NaN,21.0,NaN,NaN,NaN,CalFresh,NaN,2025551212,fax,NaN
39,41,29.0,NaN,NaN,NaN,1.0,Referrals,1200.0,123-456-7890,voice,NaN
40,42,29.0,NaN,NaN,NaN,1.0,Referrals,NaN,202-555-1212,fax,NaN
41,43,NaN,22.0,NaN,NaN,NaN,Information,123.0,650 372-6200,voice,222-555-INFO
42,44,NaN,22.0,NaN,NaN,NaN,Reservations,NaN,650 627-8244,fax,NaN
43,45,NaN,22.0,NaN,NaN,NaN,Hotline,NaN,800 372-6200,hotline,NaN
44,46,NaN,22.0,NaN,NaN,NaN,Rental Assistance,202.0,650 372-6200,tty,NaN
45,52,36.0,NaN,NaN,NaN,NaN,CalFresh Applications,123.0,703-555-1212,voice,NaN
46,53,NaN,NaN,8.0,NaN,NaN,Operations,101.0,123-456-7890,voice,NaN
47,54,32.0,NaN,NaN,NaN,NaN,Operations,NaN,703-444-1234,fax,NaN
48,55,32.0,NaN,NaN,NaN,NaN,Operations,101.0,650-555-1212,voice,NaN
49,56,NaN,11.0,NaN,NaN,NaN,NaN,NaN,650 365-3738,fax,NaN
50,57,NaN,NaN,NaN,22.0,NaN,Passport Photos,123.0,123-456-7890,voice,NaN
51,58,NaN,NaN,NaN,22.0,NaN,Passport Photos Fax,NaN,789-456-1230,fax,NaN
52,59,NaN,NaN,NaN,22.0,NaN,Passport Help via SMS,NaN,650-222-5555,sms,NaN
53,60,29.0,NaN,NaN,NaN,NaN,NaN,NaN,650-555-1212,sms,NaN

In [13]:
a = pd.read_csv('zomato.csv')

In [14]:
a.head(2)

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari